apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  # App
  PORT: "8000"
  API_BASE_URL: "http://app-backend:8000"
  FRONTEND_URL: "https://ingress_dns_name"
  ADMIN_PANEL_URL: "https://ingress_dns_name/admin"
  RESULT_BASE_URL: "https://ingress_dns_name"
  CORS_ALLOW_ORIGINS: "https://ingress_dns_name"

  # PostgreSQL
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "profile_db"
  POSTGRES_USER: "profile_user"

  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"