apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: "profile_db"
  POSTGRES_USER: "profile_user"
  POSTGRES_PORT: "5432"
